backend:
  name: github
  repo: twlabs/warp37-spike-docsify-decapcms
  branch: main
  client_id: {{GITHUB_CLIENT_ID}}
  base_url: http://localhost:3000
  auth_endpoint: api/auth
  auth_scope: repo

publish_mode: editorial_workflow
site_url: http://localhost:3000
display_url: http://localhost:3000

media_folder: assets/images
public_folder: /assets/images

collections:
  - name: "docs"
    label: "📚 Documentation"
    label_singular: "Document"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    sortable_fields: ["title", "date", "order"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", default: 1, value_type: "int" }
      - { label: "Category", name: "category", widget: "hidden", default: "docs" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

editor:
  preview: true
